name: Publish TESH Query to PyPI

on:
  push:
    tags:
      - "v*" # Only runs on annotated tags like v1.2.3 and v2.0.0-dev

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    environment:
      name: pypi

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Ensure tags are available for setuptools-scm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pre-commit setuptools_scm

      - name: Debug Git presence
        run: |
          git status
          git tag --contains
          ls -al .git

      - name: Run pre-commit
        run: pre-commit run --all-files

      - name: Build package
        run: python -m build

      - name: Show derived version
        run: python -m setuptools_scm

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
