name: Publish TESH Query to PyPI

on:
  push:
    tags:
      - "v*" # Only runs on version tags like v1.2.3

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Required for PyPI trusted publishing
      contents: write  # Required for creating releases

    environment:
      name: pypi
      url: https://pypi.org/project/teshq/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history needed for tag processing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Build package
        run: python -m build

      - name: Check package
        run: twine check dist/*

      - name: Test installation
        run: |
          python -m venv test_env
          source test_env/bin/activate
          pip install dist/*.whl
          # FIXED: Changed from teshquery to teshq
          python -c "import teshq; print('Import successful')" || echo "Import test failed"
          deactivate

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
          draft: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
