name: Publish TESH Query to PyPI

on:
  push:
    tags:
      - "v*" # Only runs on version tags like v1.2.3

# Limit concurrency to one workflow per ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Required for PyPI trusted publishing
      contents: read

    environment:
      name: pypi
      url: https://pypi.org/p/teshquery # Will link to the published package

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Full history needed for setuptools_scm

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11.10"
          cache: pip # Added pip caching for faster builds

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build pre-commit setuptools_scm wheel
          pip install -e ".[dev]"  # Install the package in development mode

      - name: Debug version information
        run: |
          git describe --tags
          python -m setuptools_scm
          echo "Current tag: ${GITHUB_REF#refs/tags/}"

      - name: Run quality checks
        run: |
          pre-commit run --all-files
          # Add any additional quality checks here

      - name: Build package
        run: python -m build

      - name: Verify package
        run: |
          python -m pip install twine
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true # More detailed output for troubleshooting

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
